services:
  - type: web
    name: aguaruta-backend
    env: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false  # la pones a mano en el panel
    healthCheckPath: /health
